/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Example */

#ifndef _Included_Example
#define _Included_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Example
 * Method:    gamma
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Example_gamma
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
